package com.ctrlwe.quaero.casemodule.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity representing a single investigable claim on the Quaero platform.
 *
 * <p><strong>Two-shape design — read this before touching anything.</strong>
 * Every {@code Case} carries two fundamentally different information shapes
 * simultaneously:</p>
 *
 * <ol>
 *   <li><strong>Public shape</strong> — {@link #claim} and
 *       {@link #publicEvidenceSummary} only. These are the only fields
 *       that may ever reach a user-facing HTTP response, before or during
 *       an investigation.</li>
 *   <li><strong>Internal shape</strong> — {@link #groundTruth},
 *       {@link #groundTruthExplanation}, {@link #trustedReferences},
 *       {@link #investigationHints}, and {@link #learningSummary}. These
 *       fields are consumed exclusively by the future Investigation and
 *       Submission &amp; Evaluation modules through
 *       {@code CaseService#getFullContext(Long)}. They must NEVER appear
 *       in any HTTP response. Not even structurally.</li>
 * </ol>
 *
 * <p>This entity is never returned directly from any controller method.
 * Public responses use {@code CaseFeedItem} or {@code CaseBriefResponse}
 * (explicit, field-by-field mappings). The internal shape is accessed only
 * through {@code CaseInternalContext}, which is itself never wired to any
 * controller.</p>
 *
 * <p>Cases are <strong>immutable once published</strong>. Corrections are
 * issued as new cases; no in-place edit endpoint exists.</p>
 *
 * <p>{@code trustedReferences} is stored as a newline-delimited {@code TEXT}
 * column (one URL or citation per line). This avoids a join-table dependency
 * before the Submission module defines how references will be consumed.
 * The Submission &amp; Evaluation module may split on {@code \n} when it
 * builds the post-submission feedback payload.</p>
 *
 * @author Quaero Engineering
 * @since 1.0
 */
@Entity
@Table(name = "cases")
@Getter
@Setter
@NoArgsConstructor
public class Case {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ----------------------------------------------------------------
    // PUBLIC SHAPE — safe to expose in public API responses
    // ----------------------------------------------------------------

    /**
     * The real-world claim this case asks the user to investigate.
     * This is the primary visible text on the Feed card and the Brief screen.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String claim;

    /**
     * A curated summary of publicly available evidence relevant to the claim.
     * This is shown in full on the Brief screen ({@code CaseBriefResponse})
     * and truncated to a teaser on the Feed ({@code CaseFeedItem}).
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String publicEvidenceSummary;

    // ----------------------------------------------------------------
    // INTERNAL SHAPE — server-side only, NEVER in any public response
    // ----------------------------------------------------------------

    /**
     * The verified factual conclusion about the claim.
     * Internal to AI grading; never exposed to users pre-submission.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String groundTruth;

    /**
     * The explanation of why {@link #groundTruth} is correct.
     * Shown to the user only after they submit, via the Submission &amp;
     * Evaluation module — not by this module.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String groundTruthExplanation;

    /**
     * Newline-delimited list of trusted references (URLs / citations).
     * One reference per line. Used by the Submission &amp; Evaluation module
     * when assembling post-submission feedback.
     * Internal only — never exposed to users pre-submission.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String trustedReferences;

    /**
     * Internal hints used by the future AI Mentor to guide Socratic
     * questioning during an investigation session. Never exposed to users.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String investigationHints;

    /**
     * A structured learning summary revealed to the user only after
     * they submit their reasoning, via the Submission &amp; Evaluation module.
     * Never exposed to users pre-submission.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String learningSummary;

    // ----------------------------------------------------------------
    // Lifecycle metadata
    // ----------------------------------------------------------------

    /**
     * Lifecycle status of the case. Only {@link CaseStatus#PUBLISHED}
     * cases are returned by public endpoints.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private CaseStatus status;

    /**
     * Timestamp at which this case record was created (set once, never updated).
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Convenience constructor for seed-data / testing use.
     * Sets {@link #createdAt} to the supplied timestamp.
     *
     * @param claim                   the investigable claim
     * @param publicEvidenceSummary   public-facing evidence summary
     * @param groundTruth             the verified conclusion (internal)
     * @param groundTruthExplanation  explanation of the conclusion (internal)
     * @param trustedReferences       newline-delimited references (internal)
     * @param investigationHints      AI-Mentor hints (internal)
     * @param learningSummary         post-submission learning text (internal)
     * @param status                  the lifecycle status
     * @param createdAt               creation timestamp
     */
    public Case(String claim,
                String publicEvidenceSummary,
                String groundTruth,
                String groundTruthExplanation,
                String trustedReferences,
                String investigationHints,
                String learningSummary,
                CaseStatus status,
                LocalDateTime createdAt) {
        this.claim = claim;
        this.publicEvidenceSummary = publicEvidenceSummary;
        this.groundTruth = groundTruth;
        this.groundTruthExplanation = groundTruthExplanation;
        this.trustedReferences = trustedReferences;
        this.investigationHints = investigationHints;
        this.learningSummary = learningSummary;
        this.status = status;
        this.createdAt = createdAt;
    }
}
