package com.ctrlwe.quaero.casemodule.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity representing a single investigable claim — an
 * <strong>Investigation Challenge</strong> — on the Quaero platform.
 *
 * <p><strong>Three-shape design — read this before touching anything.</strong>
 * Every {@code Case} carries three conceptually distinct information
 * shapes simultaneously:</p>
 *
 * <ol>
 *   <li><strong>Public shape</strong> — {@link #claim} and
 *       {@link #publicEvidenceSummary}. These are the investigative
 *       content fields visible to the user before and during an
 *       investigation.</li>
 *   <li><strong>Presentation metadata</strong> (V2 "Original Post") —
 *       {@link #platform}, {@link #originalPoster}, {@link #caption},
 *       {@link #thumbnailUrl}, {@link #mediaUrl}, {@link #mediaType},
 *       engagement metrics, {@link #verificationDifficulty},
 *       {@link #publishedAt}, and {@link #category}. These describe
 *       <em>how</em> the claim appeared on social media and are safe
 *       to expose in public responses ({@code CaseFeedItem},
 *       {@code CaseBriefResponse}).</li>
 *   <li><strong>Internal shape</strong> — {@link #groundTruth},
 *       {@link #groundTruthExplanation}, {@link #trustedReferences},
 *       {@link #investigationHints}, and {@link #learningSummary}.
 *       Consumed exclusively by Investigation and Submission modules
 *       through {@code CaseService#getFullContext(Long)}. Must NEVER
 *       appear in any HTTP response.</li>
 * </ol>
 *
 * <p>This entity is never returned directly from any controller method.
 * Public responses use {@code CaseFeedItem} or {@code CaseBriefResponse}
 * (explicit, field-by-field mappings). The internal shape is accessed only
 * through {@code CaseInternalContext}, which is itself never wired to any
 * controller.</p>
 *
 * <p>Cases are <strong>immutable once published</strong>. Corrections are
 * issued as new cases; no in-place edit endpoint exists.</p>
 *
 * <p>{@code trustedReferences} is stored as a newline-delimited {@code TEXT}
 * column (one URL or citation per line). This avoids a join-table dependency
 * before the Submission module defines how references will be consumed.
 * The Submission &amp; Evaluation module may split on {@code \n} when it
 * builds the post-submission feedback payload.</p>
 *
 * @author Quaero Engineering
 * @since 1.0
 */
@Entity
@Table(name = "cases")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Case {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ----------------------------------------------------------------
    // PUBLIC SHAPE — safe to expose in public API responses
    // ----------------------------------------------------------------

    /**
     * The real-world claim this Investigation Challenge asks the user
     * to investigate. This is the primary visible text on the
     * Investigation Feed card and the Observe screen.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String claim;

    /**
     * A curated summary of publicly available evidence relevant to the
     * claim. This is shown in full on the Observe screen
     * ({@code CaseBriefResponse}) and truncated to a teaser on the
     * Investigation Feed ({@code CaseFeedItem}).
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String publicEvidenceSummary;

    // ----------------------------------------------------------------
    // PRESENTATION METADATA — the "Original Post" (V2 architecture)
    //
    // These fields describe HOW the claim appeared on social media.
    // They are safe to expose in public API responses (Feed, Observe).
    // All nullable — existing cases predate this metadata and continue
    // to work without it.
    // ----------------------------------------------------------------

    /**
     * The social media platform from which the original post originated.
     * Drives platform-specific styling (logo, colour palette, layout)
     * on the frontend.
     */
    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private Platform platform;

    /**
     * The display name or handle of the original poster as it appeared
     * in the social media post. This is presentation text, not a real
     * Quaero user account — it may be fictitious or anonymised.
     */
    @Column(length = 255)
    private String originalPoster;

    /**
     * The original social media post's caption or body text. Separate
     * from {@link #claim}: the claim is the thing being investigated;
     * the caption is the social framing around it — they may differ.
     */
    @Column(columnDefinition = "TEXT")
    private String caption;

    /**
     * URL for the post's thumbnail or preview image, shown on the
     * Investigation Feed card. Recommended to be self-hosted rather
     * than hotlinked from the original platform.
     */
    @Column(length = 2048)
    private String thumbnailUrl;

    /**
     * URL for the full-size media (image or video) shown on the
     * Observe/Brief screen. Intentionally omitted from the Feed card
     * to keep the feed lightweight.
     */
    @Column(length = 2048)
    private String mediaUrl;

    /**
     * The type of media attached to the original post. Drives how the
     * frontend renders the media on the Observe screen (image viewer,
     * video player, text-only card, or screenshot frame).
     */
    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private MediaType mediaType;

    /**
     * Display-only engagement count — likes on the original post.
     * Static per Case (not live-updating). Defaults to 0.
     */
    @Column(nullable = false)
    @Builder.Default
    private Integer engagementLikes = 0;

    /**
     * Display-only engagement count — comments on the original post.
     * Static per Case (not live-updating). Defaults to 0.
     */
    @Column(nullable = false)
    @Builder.Default
    private Integer engagementComments = 0;

    /**
     * Display-only engagement count — shares/retweets on the original
     * post. Static per Case (not live-updating). Defaults to 0.
     */
    @Column(nullable = false)
    @Builder.Default
    private Integer engagementShares = 0;

    /**
     * The original social media post's claimed publish date. Distinct
     * from {@link #createdAt} (when the Case was added to QUAERO).
     */
    @Column
    private LocalDateTime publishedAt;

    /**
     * Signals investigation difficulty on the Feed card. A natural
     * future hook for difficulty-weighted XP in the Reputation module
     * (V1 Section 9, V2 Section 7). Defaults to {@link VerificationDifficulty#MEDIUM}.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private VerificationDifficulty verificationDifficulty = VerificationDifficulty.MEDIUM;

    /**
     * Topical category of the claim. Reserved per V2 Section 5 for
     * future filtering, analytics, and category-scoped leaderboards.
     * No filtering or scoring logic is built on this field yet.
     */
    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private Category category;

    // ----------------------------------------------------------------
    // INTERNAL SHAPE — server-side only, NEVER in any public response
    // ----------------------------------------------------------------

    /**
     * The verified factual conclusion about the claim.
     * Internal to AI grading; never exposed to users pre-submission.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String groundTruth;

    /**
     * The explanation of why {@link #groundTruth} is correct.
     * Shown to the user only after they submit, via the Submission &amp;
     * Evaluation module — not by this module.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String groundTruthExplanation;

    /**
     * Newline-delimited list of trusted references (URLs / citations).
     * One reference per line. Used by the Submission &amp; Evaluation module
     * when assembling post-submission feedback.
     * Internal only — never exposed to users pre-submission.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String trustedReferences;

    /**
     * Internal hints used by the AI Mentor to guide Socratic
     * questioning during an investigation session. Never exposed to users.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String investigationHints;

    /**
     * A structured learning summary revealed to the user only after
     * they submit their reasoning, via the Submission &amp; Evaluation module.
     * Never exposed to users pre-submission.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String learningSummary;

    // ----------------------------------------------------------------
    // Lifecycle metadata
    // ----------------------------------------------------------------

    /**
     * Lifecycle status of the case. Only {@link CaseStatus#PUBLISHED}
     * cases are returned by public endpoints.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private CaseStatus status;

    /**
     * Timestamp at which this case record was created (set once, never updated).
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
