package com.ctrlwe.quaero.user;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * JPA entity representing a registered user on the Quaero platform.
 *
 * <p>Each user has a unique {@link #username} and {@link #email},
 * a hashed {@link #password}, and profile metadata such as
 * {@link #fullName}, {@link #bio}, and {@link #profilePictureUrl}.
 * The {@link #role} and {@link #accountStatus} fields govern
 * authorisation and lifecycle state respectively.</p>
 *
 * <p>Timestamp fields ({@link #createdAt}, {@link #updatedAt}) are
 * managed automatically by JPA auditing via
 * {@link AuditingEntityListener}. The {@code createdAt} column is
 * set once at insert time and never updated; {@code updatedAt} is
 * refreshed on every modification.</p>
 *
 * <p>This entity is never returned directly from any controller
 * method. Public responses use dedicated DTOs
 * ({@link com.ctrlwe.quaero.user.dto.UserProfileResponse},
 * {@link com.ctrlwe.quaero.user.dto.UserSummaryResponse}) built
 * through explicit, field-by-field mapping in
 * {@link UserMapper}.</p>
 *
 * @author Quaero Engineering
 * @since 1.0
 */
@Entity
@Table(name = "users")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique display name chosen by the user during registration.
     * Must not contain whitespace and is between 3 and 50 characters.
     */
    @Column(nullable = false, unique = true, length = 50)
    private String username;

    /**
     * Unique email address associated with the account.
     * Used as the primary credential identifier during login.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * BCrypt-hashed password. Never returned in any API response.
     */
    @Column(nullable = false)
    private String password;

    /**
     * User's full display name (optional profile field).
     */
    @Column(length = 100)
    private String fullName;

    /**
     * URL pointing to the user's profile picture (optional).
     */
    @Column(length = 500)
    private String profilePictureUrl;

    /**
     * Short biographical text displayed on the user's profile (optional).
     */
    @Column(columnDefinition = "TEXT")
    private String bio;

    /**
     * The user's authorisation role within the platform.
     * Defaults to {@link Role#USER} at registration.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private Role role = Role.USER;

    /**
     * Lifecycle status of the account.
     * Defaults to {@link AccountStatus#ACTIVE} at registration.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private AccountStatus accountStatus = AccountStatus.ACTIVE;

    /**
     * Cumulative reputation score earned through platform engagement.
     * Starts at zero and increases through successful investigations.
     */
    @Column(nullable = false)
    @Builder.Default
    private int reputationScore = 0;

    /**
     * Timestamp at which this user record was created.
     * Set once by JPA auditing — never updated.
     */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the most recent modification to this user record.
     * Updated automatically by JPA auditing on every save.
     */
    @LastModifiedDate
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}
