package com.ctrlwe.quaero.investigation.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity representing a single message turn within an
 * {@link InvestigationSession}.
 *
 * <p>Every turn belongs to exactly one session (referenced by
 * {@code sessionId}). The session is referenced as a plain
 * {@code Long} foreign-key value — not a JPA {@code @ManyToOne} —
 * to keep the entity self-contained and allow bulk loading by session ID
 * without triggering an N+1 join. Referential integrity is enforced at
 * the database level by the FK constraint on {@code session_id}.</p>
 *
 * <h3>Sender roles</h3>
 * <p>Each turn is tagged with a {@link TurnSender} ({@code USER} or
 * {@code AI}) so that conversation history can be replayed in order
 * and assembled into a prompt without ambiguity.</p>
 *
 * <h3>Content storage</h3>
 * <p>The {@code content} column is mapped as {@code TEXT} to accommodate
 * arbitrarily long AI replies and detailed user messages without hitting
 * a VARCHAR length ceiling.</p>
 *
 * @author Quaero Engineering
 * @since 1.0
 */
@Entity
@Table(name = "conversation_turns")
@Getter
@Setter
@NoArgsConstructor
public class ConversationTurn {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * FK to the parent {@link InvestigationSession}.
     * Stored as a plain {@code Long} to respect the intra-module
     * entity boundary — no {@code @ManyToOne} join is used here.
     */
    @Column(name = "session_id", nullable = false)
    private Long sessionId;

    /**
     * Indicates who authored this turn: the user or the AI Mentor.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private TurnSender sender;

    /**
     * The full textual content of this turn.
     * Stored as {@code TEXT} to support AI replies of arbitrary length.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    /**
     * Timestamp at which this turn was created (set once, never updated).
     * Drives the ordering in
     * {@link com.ctrlwe.quaero.investigation.repository.ConversationTurnRepository#findBySessionIdOrderByCreatedAt(Long)}.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Convenience constructor for service-layer use.
     *
     * @param sessionId the ID of the parent session
     * @param sender    the turn originator ({@code USER} or {@code AI})
     * @param content   the textual content of the turn
     * @param createdAt the creation timestamp
     */
    public ConversationTurn(Long sessionId, TurnSender sender, String content,
                            LocalDateTime createdAt) {
        this.sessionId = sessionId;
        this.sender = sender;
        this.content = content;
        this.createdAt = createdAt;
    }
}
