package com.ctrlwe.quaero.investigation.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * JPA entity representing a single investigation session between one user
 * and one case on the Quaero platform.
 *
 * <h3>One-session-per-user-per-case invariant</h3>
 * <p>The composite unique constraint on {@code (user_id, case_id)} —
 * scoped to {@link SessionStatus#ACTIVE} sessions only via the
 * {@link com.ctrlwe.quaero.investigation.repository.InvestigationSessionRepository}
 * — ensures that no duplicate active sessions can exist for the same
 * user/case pair. The service layer enforces this through
 * {@code startOrResumeSession}, which does a find-or-create rather than
 * always creating. The DB unique constraint is a safety net only.</p>
 *
 * <h3>Ownership and security scope</h3>
 * <p>Every repository query in the Investigation module scopes by
 * {@code userId}. It is never permissible to look up a session by
 * {@code caseId} alone — doing so would allow a user to access another
 * user's conversation history.</p>
 *
 * <h3>Turn counting</h3>
 * <p>{@code turnCount} is incremented by the service on every completed
 * exchange (user message + AI reply = 1 turn). It is a denormalised
 * convenience field — the authoritative history is always the
 * {@link ConversationTurn} rows belonging to this session.</p>
 *
 * @author Quaero Engineering
 * @since 1.0
 */
@Entity
@Table(
    name = "investigation_sessions",
    uniqueConstraints = @UniqueConstraint(
        name = "uq_session_user_case",
        columnNames = {"user_id", "case_id"}
    )
)
@Getter
@Setter
@NoArgsConstructor
public class InvestigationSession {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * ID of the authenticated user who owns this session.
     * Sourced from the JWT security context — never from request body.
     * Scopes every session query to the owning user.
     */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /**
     * ID of the {@link com.ctrlwe.quaero.casemodule.entity.Case} being
     * investigated in this session. Stored as a plain foreign-key value
     * (not a JPA {@code @ManyToOne}) to respect the module boundary rule:
     * the Investigation module must never hold a direct JPA reference into
     * the Case module's entity graph.
     */
    @Column(name = "case_id", nullable = false)
    private Long caseId;

    /**
     * Current lifecycle status of the session.
     * Starts as {@link SessionStatus#ACTIVE} and transitions to
     * {@link SessionStatus#SUBMITTED} when the user finalises their verdict.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private SessionStatus status;

    /**
     * Total number of completed exchanges (one USER turn + one AI turn = 1).
     * Incremented atomically by the service on every successful
     * {@code postMessage} call. Used as a lightweight progress indicator
     * and, in future versions, as the trigger for the soft-nudge signal.
     */
    @Column(nullable = false)
    private int turnCount;

    /**
     * Timestamp at which this session was created (set once, never updated).
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Convenience constructor for service-layer use.
     *
     * @param userId    the ID of the session owner
     * @param caseId    the ID of the case being investigated
     * @param status    the initial lifecycle status (always {@link SessionStatus#ACTIVE})
     * @param createdAt the creation timestamp
     */
    public InvestigationSession(Long userId, Long caseId, SessionStatus status,
                                LocalDateTime createdAt) {
        this.userId = userId;
        this.caseId = caseId;
        this.status = status;
        this.turnCount = 0;
        this.createdAt = createdAt;
    }
}
