package com.ctrlwe.quaero.investigation.entity;

/**
 * Identifies the originator of a single {@link ConversationTurn}.
 *
 * <p>Every turn in the investigation dialogue is tagged with exactly one
 * sender role. This allows conversation history to be replayed correctly
 * and prevents any ambiguity when assembling the prompt sent to the AI.</p>
 *
 * @author Quaero Engineering
 * @since 1.0
 */
public enum TurnSender {

    /**
     * The turn was authored by the authenticated user who owns the session.
     */
    USER,

    /**
     * The turn was generated by the AI Mentor (via the Gemini backend,
     * accessed through {@link com.ctrlwe.quaero.ai.service.AiClientService}).
     */
    AI
}
