package com.ctrlwe.quaero.submission.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * JPA entity representing a user's evidence submission for a particular
 * case on the Quaero platform.
 *
 * <p>A submission captures the user's reasoning, source references,
 * and confidence level when evaluating a claim.</p>
 *
 * <h3>Cross-module boundary rule</h3>
 * <p>This entity belongs exclusively to the {@code submission} module.
 * It must NOT hold {@code @ManyToOne} associations to entities owned
 * by other modules (e.g. {@code Case} from {@code casemodule}, or
 * {@code User} from {@code user}). Instead, foreign keys are stored
 * as plain {@code Long} columns ({@link #caseId}, {@link #userId}).
 * Cross-module queries must go through the owning module's service
 * interface — never via JPA joins across module boundaries.</p>
 *
 * <p>Lifecycle: submissions are created in {@link SubmissionStatus#PENDING}
 * state and transition to {@link SubmissionStatus#VERIFIED} or
 * {@link SubmissionStatus#REJECTED} after evaluation.</p>
 *
 * <p>Timestamp fields ({@link #createdAt}, {@link #updatedAt}) are
 * managed automatically by JPA auditing via
 * {@link AuditingEntityListener}.</p>
 *
 * @author Quaero Engineering
 * @since 1.0
 */
@Entity
@Table(name = "submissions")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Submission {

    /**
     * Surrogate primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Foreign key to the {@code cases} table.
     *
     * <p>Stored as a plain {@code Long} — no {@code @ManyToOne} association
     * to {@code Case}. To load case data, use {@code CaseService.getFullContext()}
     * or {@code CaseService.getBrief()} via the case module's service interface.</p>
     */
    @Column(name = "case_id", nullable = false)
    private Long caseId;

    /**
     * Foreign key to the {@code users} table.
     *
     * <p>Stored as a plain {@code Long} — no {@code @ManyToOne} association
     * to {@code User}. To load user data, use {@code UserService.getProfile()}
     * via the user module's service interface.</p>
     */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    /**
     * A concise title summarising the submission's claim or argument.
     */
    @Column(nullable = false, length = 255)
    private String title;

    /**
     * The full body of the submission, containing the user's reasoning
     * and analysis.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    /**
     * The name of the primary source referenced in the submission
     * (e.g. publication name, author, or organisation).
     */
    @Column(length = 255)
    private String sourceName;

    /**
     * The URL of the primary source referenced in the submission.
     */
    @Column(length = 2048)
    private String sourceUrl;

    /**
     * The category of evidence provided in this submission.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private EvidenceType evidenceType = EvidenceType.OTHER;

    /**
     * The submitter's self-assessed confidence in the accuracy of
     * their evidence and reasoning.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private ConfidenceLevel confidenceLevel = ConfidenceLevel.MEDIUM;

    /**
     * The current lifecycle status of this submission.
     * Defaults to {@link SubmissionStatus#PENDING} at creation.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private SubmissionStatus status = SubmissionStatus.PENDING;

    /**
     * Timestamp at which this submission was created.
     * Set once by JPA auditing — never updated.
     */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the most recent modification to this submission.
     * Updated automatically by JPA auditing on every save.
     */
    @LastModifiedDate
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}
